/*
 * CKAN API
 *
 * Comprehensive Open Data Knowledge (CKAN) REST API for data management and publishing.  CKAN is a powerful data management system that makes data accessible by providing tools to streamline publishing, sharing, finding and using data. This API provides programmatic access to all CKAN functionality including:  - Dataset (Package) management - create, read, update, delete datasets - Resource management - manage files and data resources within datasets   - Organization and Group management - organize datasets into logical groupings - User management - manage user accounts and permissions - Search functionality - powerful search across all data - Metadata and tagging - rich metadata and taxonomy support - Data validation and quality - ensure data integrity  The API follows REST principles and returns JSON responses. Most endpoints support both GET and POST methods.  ## API Versions  - **API v3** (default): Main action API at `/api/3/action/{action}` - **Utility API v1/v2**: Autocomplete and utility functions at `/api/{version}/util/` - **Legacy API v1**: Basic API information at `/api/1`  ## Authentication  Many API calls require authentication via API key passed as: - HTTP Header: `Authorization: {api_key}` - URL Parameter: `?api_key={api_key}`  - POST Data: `{\"api_key\": \"{api_key}\"}`  ## Error Handling  All API responses include: - `success`: Boolean indicating if the request was successful - `result`: The actual data (on success) or error details (on failure) - `help`: URL to documentation for the action  Error responses include structured error information with error type and detailed messages.
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// A group or an organization.
///
/// CKAN models both with one type and tells them apart with
/// [`Self::is_organization`]. An organization owns datasets and controls who
/// may edit them; a group is a looser collection a dataset can belong to.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Group {
    /// Unique identifier for the group or organization.
    ///
    /// CKAN's `id` column is unconstrained text; see [`crate::models::Package::id`]
    /// for why this is a `String` rather than a `uuid::Uuid`. This is not
    /// hypothetical here: some deployments create organizations with an
    /// explicit slug id (e.g. Ireland's national open-data portal has an
    /// organization with `id: "central-statistics-office"`).
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// URL-friendly name
    #[serde(rename = "name")]
    pub name: String,
    /// Human-readable title
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Group description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// URL to group image
    #[serde(rename = "image_url", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    /// Fully-qualified URL of the image, resolved by the portal.
    ///
    /// [`Self::image_url`] may be relative to the site, so prefer this one when
    /// fetching the image.
    #[serde(rename = "image_display_url", skip_serializing_if = "Option::is_none")]
    pub image_display_url: Option<String>,
    /// The group type, `group` or `organization` by default.
    ///
    /// A portal with a custom group-type extension can send others.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Whether the group is active or has been deleted.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    /// Whether a site administrator has approved the group.
    #[serde(rename = "approval_status", skip_serializing_if = "Option::is_none")]
    pub approval_status: Option<String>,
    /// Whether this is an organization rather than a plain group.
    ///
    /// This is the only thing separating the two, since CKAN returns both
    /// through this type.
    #[serde(rename = "is_organization", skip_serializing_if = "Option::is_none")]
    pub is_organization: Option<bool>,
    /// When the group was created, as an ISO 8601 timestamp.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// Number of packages in this group
    #[serde(rename = "package_count", skip_serializing_if = "Option::is_none")]
    pub package_count: Option<i32>,
    /// Members of the group, present only when the call asked for them.
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<models::User>>,
    /// Parent groups this group belongs to.
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<models::Group>>,
    /// Free-form key/value pairs attached to the group.
    #[serde(rename = "extras", skip_serializing_if = "Option::is_none")]
    pub extras: Option<std::collections::HashMap<String, String>>,
}

impl Group {
    /// Create a [`Group`] with the required `name`; every other field starts as
    /// `None`.
    pub fn new(name: String) -> Group {
        Group {
            id: None,
            name,
            title: None,
            description: None,
            image_url: None,
            image_display_url: None,
            r#type: None,
            state: None,
            approval_status: None,
            is_organization: None,
            created: None,
            package_count: None,
            users: None,
            groups: None,
            extras: None,
        }
    }
}
/// Whether a group is live or has been deleted.
#[derive(
    Clone, Copy, Debug, Default, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize,
)]
pub enum State {
    /// The group is live.
    #[serde(rename = "active")]
    #[default]
    Active,
    /// The group has been deleted. CKAN deletes softly, so the record is still
    /// returned.
    #[serde(rename = "deleted")]
    Deleted,
}
