/*
 * CKAN API
 *
 * Comprehensive Open Data Knowledge (CKAN) REST API for data management and publishing.  CKAN is a powerful data management system that makes data accessible by providing tools to streamline publishing, sharing, finding and using data. This API provides programmatic access to all CKAN functionality including:  - Dataset (Package) management - create, read, update, delete datasets - Resource management - manage files and data resources within datasets   - Organization and Group management - organize datasets into logical groupings - User management - manage user accounts and permissions - Search functionality - powerful search across all data - Metadata and tagging - rich metadata and taxonomy support - Data validation and quality - ensure data integrity  The API follows REST principles and returns JSON responses. Most endpoints support both GET and POST methods.  ## API Versions  - **API v3** (default): Main action API at `/api/3/action/{action}` - **Utility API v1/v2**: Autocomplete and utility functions at `/api/{version}/util/` - **Legacy API v1**: Basic API information at `/api/1`  ## Authentication  Many API calls require authentication via API key passed as: - HTTP Header: `Authorization: {api_key}` - URL Parameter: `?api_key={api_key}`  - POST Data: `{\"api_key\": \"{api_key}\"}`  ## Error Handling  All API responses include: - `success`: Boolean indicating if the request was successful - `result`: The actual data (on success) or error details (on failure) - `help`: URL to documentation for the action  Error responses include structured error information with error type and detailed messages.
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Resource {
    /// Unique identifier for the resource.
    ///
    /// CKAN's `id` column is unconstrained text; see [`crate::models::Package::id`]
    /// for why this is a `String` rather than a `uuid::Uuid`.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Identifier of the dataset this resource belongs to.
    #[serde(rename = "package_id", skip_serializing_if = "Option::is_none")]
    pub package_id: Option<String>,
    /// URL to the resource
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Description of the resource
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// File format (CSV, JSON, PDF, etc.)
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    /// Hash of the resource file
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    /// Name of the resource
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Type of resource
    #[serde(rename = "resource_type", skip_serializing_if = "Option::is_none")]
    pub resource_type: Option<String>,
    /// Type of URL (upload, api, etc.)
    #[serde(rename = "url_type", skip_serializing_if = "Option::is_none")]
    pub url_type: Option<String>,
    /// MIME type of the resource
    #[serde(rename = "mimetype", skip_serializing_if = "Option::is_none")]
    pub mimetype: Option<String>,
    /// Inner MIME type for compressed files
    #[serde(rename = "mimetype_inner", skip_serializing_if = "Option::is_none")]
    pub mimetype_inner: Option<String>,
    /// Cached URL for the resource
    #[serde(rename = "cache_url", skip_serializing_if = "Option::is_none")]
    pub cache_url: Option<String>,
    /// Size of the resource in bytes.
    ///
    /// CKAN's `resource.size` column is a `BigInteger`, so this is `i64`
    /// rather than `i32` -- an `i32` rejects any file over 2 GiB and, because
    /// `Resource` nests inside `Package.resources` inside
    /// `PackageSearchResult.results`, takes the whole page down with it.
    /// Deserialization also tolerates a numeric string (some portals send
    /// `size` as text); a non-numeric string (e.g. a human-formatted
    /// `"523 KiB"`, observed on data.qld.gov.au) degrades to `None` rather
    /// than failing the resource.
    #[serde(
        rename = "size",
        default,
        deserialize_with = "deserialize_flexible_size",
        skip_serializing_if = "Option::is_none"
    )]
    pub size: Option<i64>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "last_modified", skip_serializing_if = "Option::is_none")]
    pub last_modified: Option<String>,
    #[serde(rename = "cache_last_updated", skip_serializing_if = "Option::is_none")]
    pub cache_last_updated: Option<String>,
    /// Whether the resource is in the datastore
    #[serde(rename = "datastore_active", skip_serializing_if = "Option::is_none")]
    pub datastore_active: Option<bool>,
}

impl Resource {
    pub fn new() -> Resource {
        Resource {
            id: None,
            package_id: None,
            url: None,
            description: None,
            format: None,
            hash: None,
            name: None,
            resource_type: None,
            url_type: None,
            mimetype: None,
            mimetype_inner: None,
            cache_url: None,
            size: None,
            created: None,
            last_modified: None,
            cache_last_updated: None,
            datastore_active: None,
        }
    }
}

/// Accepts `resource.size` as a JSON number, a numeric string, or a
/// non-numeric string, in that order of preference.
///
/// A JSON number widens straight to `i64`. A string is tried as a decimal
/// integer first; when that fails -- a human-formatted value such as
/// `"523 KiB"`, observed on a live portal -- the field degrades to `None`
/// rather than failing deserialization. A missing or `null` field also
/// yields `None`. One resource's unparseable size must never fail the
/// dataset it belongs to.
fn deserialize_flexible_size<'de, D>(deserializer: D) -> Result<Option<i64>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = Option::<serde_json::Value>::deserialize(deserializer)?;
    Ok(match value {
        Some(serde_json::Value::Number(n)) => n.as_i64(),
        Some(serde_json::Value::String(s)) => s.trim().parse::<i64>().ok(),
        _ => None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn size_of(value: serde_json::Value) -> Option<i64> {
        let resource: Resource =
            serde_json::from_value(json!({ "size": value })).expect("Resource must deserialize");
        resource.size
    }

    #[test]
    fn deserialize_flexible_size_accepts_a_json_integer() {
        assert_eq!(size_of(json!(523)), Some(523));
    }

    #[test]
    fn deserialize_flexible_size_accepts_a_numeric_string() {
        assert_eq!(size_of(json!("523")), Some(523));
    }

    /// serde_json::Number::as_i64() returns None for any number written
    /// with a decimal point, even a whole one -- 523.0 is stored as the
    /// Float variant internally, and as_i64() never inspects Float. A
    /// CKAN-compatible backend whose JSON encoder always emits floats for
    /// numeric fields would otherwise lose every size.
    #[test]
    fn deserialize_flexible_size_accepts_an_integral_json_float() {
        assert_eq!(size_of(json!(523.0)), Some(523));
    }

    #[test]
    fn deserialize_flexible_size_rejects_a_non_integral_json_float() {
        assert_eq!(size_of(json!(523.7)), None);
    }

    #[test]
    fn deserialize_flexible_size_degrades_a_non_numeric_string_to_none() {
        assert_eq!(size_of(json!("523 KiB")), None);
    }

    #[test]
    fn deserialize_flexible_size_treats_null_as_none() {
        assert_eq!(size_of(json!(null)), None);
    }

    #[test]
    fn deserialize_flexible_size_treats_empty_string_as_none() {
        assert_eq!(size_of(json!("")), None);
    }

    /// A value with no fractional part but too large for i64 (parsed as the
    /// Float variant, since it doesn't fit u64 either) must still degrade to
    /// None rather than truncating to a wrong-but-plausible i64.
    #[test]
    fn deserialize_flexible_size_rejects_a_value_beyond_i64_max() {
        let beyond_i64_max: serde_json::Value =
            serde_json::from_str("99999999999999999999999999999999").expect("valid JSON number");
        assert_eq!(size_of(beyond_i64_max), None);
    }
}
