/*
 * CKAN API
 *
 * Comprehensive Open Data Knowledge (CKAN) REST API for data management and publishing.  CKAN is a powerful data management system that makes data accessible by providing tools to streamline publishing, sharing, finding and using data. This API provides programmatic access to all CKAN functionality including:  - Dataset (Package) management - create, read, update, delete datasets - Resource management - manage files and data resources within datasets   - Organization and Group management - organize datasets into logical groupings - User management - manage user accounts and permissions - Search functionality - powerful search across all data - Metadata and tagging - rich metadata and taxonomy support - Data validation and quality - ensure data integrity  The API follows REST principles and returns JSON responses. Most endpoints support both GET and POST methods.  ## API Versions  - **API v3** (default): Main action API at `/api/3/action/{action}` - **Utility API v1/v2**: Autocomplete and utility functions at `/api/{version}/util/` - **Legacy API v1**: Basic API information at `/api/1`  ## Authentication  Many API calls require authentication via API key passed as: - HTTP Header: `Authorization: {api_key}` - URL Parameter: `?api_key={api_key}`  - POST Data: `{\"api_key\": \"{api_key}\"}`  ## Error Handling  All API responses include: - `success`: Boolean indicating if the request was successful - `result`: The actual data (on success) or error details (on failure) - `help`: URL to documentation for the action  Error responses include structured error information with error type and detailed messages.
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// What the portal reports about itself.
///
/// Returned by `status_show`. Useful mainly for [`Self::ckan_version`] and
/// [`Self::extensions`], which together say which actions a deployment
/// actually supports.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusInfo {
    /// The portal's title.
    #[serde(rename = "site_title", skip_serializing_if = "Option::is_none")]
    pub site_title: Option<String>,
    /// The portal's description.
    #[serde(rename = "site_description", skip_serializing_if = "Option::is_none")]
    pub site_description: Option<String>,
    /// The portal's own base URL.
    #[serde(rename = "site_url", skip_serializing_if = "Option::is_none")]
    pub site_url: Option<String>,
    /// Which CKAN release the portal runs.
    ///
    /// Worth checking before relying on a newer action: this crate targets the
    /// v3 Action API, but individual actions came in at different releases.
    #[serde(rename = "ckan_version", skip_serializing_if = "Option::is_none")]
    pub ckan_version: Option<String>,
    /// Where the portal sends its error reports.
    #[serde(rename = "error_emails_to", skip_serializing_if = "Option::is_none")]
    pub error_emails_to: Option<String>,
    /// The portal's default locale.
    #[serde(rename = "locale_default", skip_serializing_if = "Option::is_none")]
    pub locale_default: Option<String>,
    /// Extensions the portal has enabled.
    ///
    /// An extension can add actions and fields beyond core CKAN, which is one
    /// reason a response may carry more than these models name.
    #[serde(rename = "extensions", skip_serializing_if = "Option::is_none")]
    pub extensions: Option<Vec<String>>,
}

impl StatusInfo {
    /// Create an empty [`StatusInfo`]; every field starts as `None`.
    pub fn new() -> StatusInfo {
        StatusInfo {
            site_title: None,
            site_description: None,
            site_url: None,
            ckan_version: None,
            error_emails_to: None,
            locale_default: None,
            extensions: None,
        }
    }
}
