/*
 * CKAN API
 *
 * Comprehensive Open Data Knowledge (CKAN) REST API for data management and publishing.  CKAN is a powerful data management system that makes data accessible by providing tools to streamline publishing, sharing, finding and using data. This API provides programmatic access to all CKAN functionality including:  - Dataset (Package) management - create, read, update, delete datasets - Resource management - manage files and data resources within datasets   - Organization and Group management - organize datasets into logical groupings - User management - manage user accounts and permissions - Search functionality - powerful search across all data - Metadata and tagging - rich metadata and taxonomy support - Data validation and quality - ensure data integrity  The API follows REST principles and returns JSON responses. Most endpoints support both GET and POST methods.  ## API Versions  - **API v3** (default): Main action API at `/api/3/action/{action}` - **Utility API v1/v2**: Autocomplete and utility functions at `/api/{version}/util/` - **Legacy API v1**: Basic API information at `/api/1`  ## Authentication  Many API calls require authentication via API key passed as: - HTTP Header: `Authorization: {api_key}` - URL Parameter: `?api_key={api_key}`  - POST Data: `{\"api_key\": \"{api_key}\"}`  ## Error Handling  All API responses include: - `success`: Boolean indicating if the request was successful - `result`: The actual data (on success) or error details (on failure) - `help`: URL to documentation for the action  Error responses include structured error information with error type and detailed messages.
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// One tag attached to a dataset.
///
/// A tag with no [`Self::vocabulary_id`] is free-form. One that names a
/// vocabulary is drawn from that controlled list instead.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tag {
    /// Unique identifier for the tag.
    ///
    /// CKAN's `id` column is unconstrained text; see [`crate::models::Package::id`]
    /// for why this is a `String` rather than a `uuid::Uuid`.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Tag name
    #[serde(rename = "name")]
    pub name: String,
    /// Display name for the tag
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Whether the tag is active or has been deleted.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    /// ID of vocabulary this tag belongs to
    #[serde(rename = "vocabulary_id", skip_serializing_if = "Option::is_none")]
    pub vocabulary_id: Option<String>,
}

impl Tag {
    /// Create a [`Tag`] with the required `name`; every other field starts as
    /// `None`.
    pub fn new(name: String) -> Tag {
        Tag {
            id: None,
            name,
            display_name: None,
            state: None,
            vocabulary_id: None,
        }
    }
}
/// Whether a tag is live or has been deleted.
#[derive(
    Clone, Copy, Debug, Default, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize,
)]
pub enum State {
    /// The tag is live.
    #[serde(rename = "active")]
    #[default]
    Active,
    /// The tag has been deleted. CKAN deletes softly, so the record is still
    /// returned.
    #[serde(rename = "deleted")]
    Deleted,
}
