/*
 * CKAN API
 *
 * Comprehensive Open Data Knowledge (CKAN) REST API for data management and publishing.  CKAN is a powerful data management system that makes data accessible by providing tools to streamline publishing, sharing, finding and using data. This API provides programmatic access to all CKAN functionality including:  - Dataset (Package) management - create, read, update, delete datasets - Resource management - manage files and data resources within datasets   - Organization and Group management - organize datasets into logical groupings - User management - manage user accounts and permissions - Search functionality - powerful search across all data - Metadata and tagging - rich metadata and taxonomy support - Data validation and quality - ensure data integrity  The API follows REST principles and returns JSON responses. Most endpoints support both GET and POST methods.  ## API Versions  - **API v3** (default): Main action API at `/api/3/action/{action}` - **Utility API v1/v2**: Autocomplete and utility functions at `/api/{version}/util/` - **Legacy API v1**: Basic API information at `/api/1`  ## Authentication  Many API calls require authentication via API key passed as: - HTTP Header: `Authorization: {api_key}` - URL Parameter: `?api_key={api_key}`  - POST Data: `{\"api_key\": \"{api_key}\"}`  ## Error Handling  All API responses include: - `success`: Boolean indicating if the request was successful - `result`: The actual data (on success) or error details (on failure) - `help`: URL to documentation for the action  Error responses include structured error information with error type and detailed messages.
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// A user account.
///
/// How much of this a caller sees depends on who is asking:
/// [`Self::email`] and [`Self::sysadmin`] are withheld from anonymous
/// requests.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// Unique identifier for the user.
    ///
    /// CKAN's `id` column is unconstrained text; see [`crate::models::Package::id`]
    /// for why this is a `String` rather than a `uuid::Uuid`.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Username (unique identifier)
    #[serde(rename = "name")]
    pub name: String,
    /// Full display name
    #[serde(rename = "fullname", skip_serializing_if = "Option::is_none")]
    pub fullname: Option<String>,
    /// Computed display name
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// The user's email address.
    ///
    /// Returned only to a caller entitled to see it - anonymous requests get
    /// `None` rather than an error.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// User biography/about text
    #[serde(rename = "about", skip_serializing_if = "Option::is_none")]
    pub about: Option<String>,
    /// When the account was created, as an ISO 8601 timestamp.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// Whether user is a system administrator
    #[serde(rename = "sysadmin", skip_serializing_if = "Option::is_none")]
    pub sysadmin: Option<bool>,
    /// Whether the account is active, deleted, or not yet activated.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    /// URL of the user's avatar, possibly relative to the site.
    #[serde(rename = "image_url", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    /// Fully-qualified URL of the avatar, resolved by the portal.
    ///
    /// Prefer this over [`Self::image_url`] when fetching the image.
    #[serde(rename = "image_display_url", skip_serializing_if = "Option::is_none")]
    pub image_display_url: Option<String>,
    /// Number of packages created by this user
    #[serde(
        rename = "number_created_packages",
        skip_serializing_if = "Option::is_none"
    )]
    pub number_created_packages: Option<i32>,
}

impl User {
    /// Create a [`User`] with the required `name`; every other field starts as
    /// `None`.
    pub fn new(name: String) -> User {
        User {
            id: None,
            name,
            fullname: None,
            display_name: None,
            email: None,
            about: None,
            created: None,
            sysadmin: None,
            state: None,
            image_url: None,
            image_display_url: None,
            number_created_packages: None,
        }
    }
}
/// Whether a user account is live, deleted, or not yet activated.
#[derive(
    Clone, Copy, Debug, Default, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize,
)]
pub enum State {
    /// The account is live.
    #[serde(rename = "active")]
    #[default]
    Active,
    /// The account has been deleted. CKAN deletes softly, so the record is
    /// still returned.
    #[serde(rename = "deleted")]
    Deleted,
    /// The account exists but has not been activated.
    #[serde(rename = "inactive")]
    Inactive,
}
