/*
 * CKAN API
 *
 * Comprehensive Open Data Knowledge (CKAN) REST API for data management and publishing.  CKAN is a powerful data management system that makes data accessible by providing tools to streamline publishing, sharing, finding and using data. This API provides programmatic access to all CKAN functionality including:  - Dataset (Package) management - create, read, update, delete datasets - Resource management - manage files and data resources within datasets   - Organization and Group management - organize datasets into logical groupings - User management - manage user accounts and permissions - Search functionality - powerful search across all data - Metadata and tagging - rich metadata and taxonomy support - Data validation and quality - ensure data integrity  The API follows REST principles and returns JSON responses. Most endpoints support both GET and POST methods.  ## API Versions  - **API v3** (default): Main action API at `/api/3/action/{action}` - **Utility API v1/v2**: Autocomplete and utility functions at `/api/{version}/util/` - **Legacy API v1**: Basic API information at `/api/1`  ## Authentication  Many API calls require authentication via API key passed as: - HTTP Header: `Authorization: {api_key}` - URL Parameter: `?api_key={api_key}`  - POST Data: `{\"api_key\": \"{api_key}\"}`  ## Error Handling  All API responses include: - `success`: Boolean indicating if the request was successful - `result`: The actual data (on success) or error details (on failure) - `help`: URL to documentation for the action  Error responses include structured error information with error type and detailed messages.
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// The error object carried by a validation failure.
///
/// CKAN also sends one entry per rejected field alongside these two members,
/// each holding an array of messages
/// (`{"name": ["Missing value"], "__type": "Validation Error"}`). Those
/// entries are not modelled here, because their names are the names of
/// whatever fields the call got wrong; read them from
/// [`crate::models::ActionResponse::error`], which keeps the raw JSON.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationErrorResponseError {
    /// Always `Validation Error` on this object.
    #[serde(rename = "__type", skip_serializing_if = "Option::is_none")]
    pub __type: Option<Type>,
    /// A summary message, where CKAN sends one.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ValidationErrorResponseError {
    /// Create an empty [`ValidationErrorResponseError`]; every field starts
    /// as `None`.
    pub fn new() -> ValidationErrorResponseError {
        ValidationErrorResponseError {
            __type: None,
            message: None,
        }
    }
}
/// The single error type this object carries.
#[derive(
    Clone, Copy, Debug, Default, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize,
)]
pub enum Type {
    /// Serialized as `Validation Error`.
    #[serde(rename = "Validation Error")]
    #[default]
    ValidationError,
}
